import mongoose, { Document, Schema } from 'mongoose';

// Message metadata sub-schema
const MessageMetadataSchema = new Schema({
  timestamp: { type: Date, default: Date.now },
  processed: { type: Boolean, default: false }, // Whether message has been processed by AI
  aiGenerated: { type: Boolean, default: false }, // Generated by AI or rules
  testMode: { type: Boolean, default: false }, // True if message was generated in test mode (not sent)
  isManual: { type: Boolean, default: false }, // True if message was sent manually by owner (not by bot)
  instagramResponse: {
    messageId: { type: String, required: false } // Instagram's message ID
  },
  // Meta's id for the outbound WhatsApp message (wamid.*). Kept separate from
  // instagramResponse so a status callback can be correlated per channel without
  // overloading one field with two different id namespaces.
  whatsappResponse: {
    messageId: { type: String, required: false },
    status: { type: String, required: false }, // sent | delivered | read | failed
    timestamp: { type: Date, required: false },
    errorCode: { type: String, required: false },
    errorMessage: { type: String, required: false }
  }
});

// Message content sub-schema
const MessageContentSchema = new Schema({
  text: { type: String, required: true } // Message text content
});

export interface IMessage extends Document {
  id: string;
  /**
   * Meta message ID. Instagram sends `mid.*`, WhatsApp sends `wamid.*`. Both are
   * globally unique and both land here — the existing `unique: true` index is
   * therefore the WhatsApp deduplication mechanism, no extra field needed.
   */
  mid: string;
  conversationId: string; // Reference to Conversation
  contactId: string; // Reference to Contact (for quick access)
  accountId: string; // InstagramAccount.accountId or WhatsappAccount.phoneNumberId
  channel: 'instagram' | 'whatsapp';
  recipientId?: string; // Instagram recipient ID (which account received the message)
  role: 'user' | 'assistant' | 'system'; // Message sender role
  content: {
    text: string;
  };
  metadata: {
    timestamp: Date;
    processed: boolean;
    aiGenerated: boolean;
    testMode?: boolean;
    isManual?: boolean; // True if message was sent manually by owner (not by bot)
    instagramResponse: {
      messageId?: string;
    };
    whatsappResponse?: {
      messageId?: string;
      status?: string;
      timestamp?: Date;
      errorCode?: string;
      errorMessage?: string;
    };
  };
  status: 'received' | 'queued' | 'processing' | 'sent' | 'failed' | 'delivered' | 'read' | 'test';
  deliveryConfirmed: boolean; // Whether delivery was confirmed by Instagram
  deliveryConfirmedAt?: Date; // When delivery was confirmed
}

const MessageSchema = new Schema<IMessage>({
  mid: { type: String, required: true, unique: true },
  conversationId: { type: String, required: true },
  contactId: { type: String, required: true },
  accountId: { type: String, required: true },
  channel: { type: String, enum: ['instagram', 'whatsapp'], default: 'instagram' },
  recipientId: { type: String, required: false }, // Instagram recipient ID
  role: { type: String, enum: ['user', 'assistant', 'system'], required: true },
  content: { type: MessageContentSchema, required: true },
  metadata: { type: MessageMetadataSchema, default: () => ({}) },
  status: { type: String, enum: ['received', 'queued', 'processing', 'sent', 'failed', 'delivered', 'read', 'test'], default: 'received' },
  deliveryConfirmed: { type: Boolean, default: false },
  deliveryConfirmedAt: { type: Date, required: false }
}, {
  timestamps: true,
  toJSON: { virtuals: true },
  toObject: { virtuals: true }
});

// Indexes for performance
MessageSchema.index({ conversationId: 1 });
MessageSchema.index({ contactId: 1 });
MessageSchema.index({ accountId: 1 });
MessageSchema.index({ channel: 1 });
MessageSchema.index({ 'metadata.whatsappResponse.messageId': 1 });
MessageSchema.index({ recipientId: 1 });
MessageSchema.index({ role: 1 });
MessageSchema.index({ status: 1 });
MessageSchema.index({ 'metadata.timestamp': -1 });
MessageSchema.index({ 'metadata.aiGenerated': 1 });
MessageSchema.index({ deliveryConfirmed: 1 });

// Pre-save middleware to update metadata
MessageSchema.pre('save', function(next) {
  // Update delivery confirmation
  if (this.isModified('deliveryConfirmed') && this.deliveryConfirmed && !this.deliveryConfirmedAt) {
    this.deliveryConfirmedAt = new Date();
  }
  
  next();
});

// Virtual for message age in seconds
MessageSchema.virtual('ageSeconds').get(function() {
  const now = new Date();
  return Math.floor((now.getTime() - this.metadata.timestamp.getTime()) / 1000);
});

// Static method to find messages by status
MessageSchema.statics.findByStatus = function(status: string) {
  return this.find({ status });
};

// Static method to find failed messages
MessageSchema.statics.findFailed = function() {
  return this.find({ status: 'failed' });
};

// Static method to find AI-generated messages
MessageSchema.statics.findAIGenerated = function() {
  return this.find({ 'metadata.aiGenerated': true });
};

// Static method to find messages by conversation
MessageSchema.statics.findByConversation = function(conversationId: string, limit: number = 50) {
  return this.find({ conversationId })
    .sort({ 'metadata.timestamp': -1 })
    .limit(limit);
};

export default mongoose.model<IMessage>('Message', MessageSchema);
